In [2]:
import pandas as pd

In [3]:
df =pd.read_csv('huge_1M_titanic.csv')

In [4]:
df.drop(columns=['PassengerId','Name','Age','Cabin','Ticket'],inplace=True)

In [5]:
df.dropna(inplace=True)
df.reset_index(drop=True, inplace=True)

df.info()

<class 'pandas.DataFrame'>
RangeIndex: 997760 entries, 0 to 997759
Data columns (total 7 columns):
 #   Column    Non-Null Count   Dtype
---  ------    --------------   -----
 0   Survived  997760 non-null  int64
 1   Pclass    997760 non-null  int64
 2   Sex       997760 non-null  str
 3   SibSp     997760 non-null  int64
 4   Parch     997760 non-null  int64
 5   Fare      997760 non-null  float64
 6   Embarked  997760 non-null  str
dtypes: float64(1), int64(4), str(2)
memory usage: 59.0 MB

In [6]:
df.isna().sum().sum()

np.int64(0)

In [6]:
df

        Survived  Pclass     Sex  SibSp  Parch        Fare Embarked
0              1       1  female      0      0   76.760165        C
1              0       3    male      0      0   10.193097        S
2              0       3    male      0      0   12.029416        C
3              0       3    male      0      0   13.429448        S
4              0       3    male      0      0    4.840769        C
...          ...     ...     ...    ...    ...         ...      ...
997755         0       2    male      0      0   26.196512        S
997756         1       1  female      0      0  102.555248        S
997757         0       3    male      1      0    8.274807        S
997758         0       2    male      1      0    0.000000        S
997759         1       1  female      1      0   57.720316        S

[997760 rows x 7 columns]

In [7]:
df['Fare'] = df['Fare'].astype('int8')

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le = LabelEncoder()
df['Sex'] = le.fit_transform(df[['Sex']])

f:\Codes\Python\Gen AI\Projects\Titanic Project\.venv\Lib\site-packages\sklearn\preprocessing\_label.py:120: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)

In [10]:
from sklearn.preprocessing import OneHotEncoder

In [11]:
df.isna().sum().sum()

np.int64(0)

In [14]:
ohe = OneHotEncoder(sparse_output=False)
df['Embarked']=df['Embarked'].replace({'S':'Southampton','C':'Cherbourg','Q':'Queenstown'})
temp = pd.DataFrame(ohe.fit_transform(df[['Embarked']]),columns=ohe.get_feature_names_out())

In [15]:
df.isna().sum().sum()

np.int64(0)

In [16]:
df=pd.concat((df,temp),axis=1)
df.drop(columns='Embarked',inplace=True)

In [15]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 997760 entries, 0 to 997759
Data columns (total 9 columns):
 #   Column                Non-Null Count   Dtype
---  ------                --------------   -----
 0   Survived              997760 non-null  int64
 1   Pclass                997760 non-null  int64
 2   Sex                   997760 non-null  int64
 3   SibSp                 997760 non-null  int64
 4   Parch                 997760 non-null  int64
 5   Fare                  997760 non-null  int8
 6   Embarked_Cherbourg    997760 non-null  float64
 7   Embarked_Queenstown   997760 non-null  float64
 8   Embarked_Southampton  997760 non-null  float64
dtypes: float64(3), int64(5), int8(1)
memory usage: 61.9 MB

In [16]:
df.head(5)

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1,1,0,0,0,76,1.0,0.0,0.0
1,0,3,1,0,0,10,0.0,0.0,1.0
2,0,3,1,0,0,12,1.0,0.0,0.0
3,0,3,1,0,0,13,0.0,0.0,1.0
4,0,3,1,0,0,4,1.0,0.0,0.0

## Feature Encoding

In [17]:
from sklearn.preprocessing import StandardScaler

In [18]:
num_col = df.select_dtypes(include='number').columns
num_col = num_col.drop('Survived')

ss = StandardScaler()
df[num_col] = ss.fit_transform(df[num_col])

In [19]:
df

,Survived,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,1,-1.568865,-1.359197,-0.462644,-0.469267,1.675922,2.083270,-0.298135,-1.648919
1,0,0.824107,0.735729,-0.462644,-0.469267,-0.234102,-0.480015,-0.298135,0.606458
2,0,0.824107,0.735729,-0.462644,-0.469267,-0.176222,2.083270,-0.298135,-1.648919
3,0,0.824107,0.735729,-0.462644,-0.469267,-0.147283,-0.480015,-0.298135,0.606458
4,0,0.824107,0.735729,-0.462644,-0.469267,-0.407741,2.083270,-0.298135,-1.648919
...,...,...,...,...,...,...,...,...,...
997755,0,-0.372379,0.735729,-0.462644,-0.469267,0.228934,-0.480015,-0.298135,0.606458
997756,1,-1.568865,-1.359197,-0.462644,-0.469267,2.428356,-0.480015,-0.298135,0.606458
997757,0,0.824107,0.735729,0.442462,-0.469267,-0.291981,-0.480015,-0.298135,0.606458
997758,0,-0.372379,0.735729,0.442462,-0.469267,-0.523500,-0.480015,-0.298135,0.606458
997759,1,-1.568865,-1.359197,0.442462,-0.469267,1.126067,-0.480015,-0.298135,0.606458

In [20]:
import pickle

In [21]:
with open('label_encoder.pkl','wb') as file:
    pickle.dump(le,file)

In [22]:
with open('one_hot_encoder.pkl','wb') as file:
    pickle.dump(ohe,file)
with open('standard_scaler.pkl','wb') as file:
    pickle.dump(ss,file)

# Train Validation Test Split

In [23]:
X = df.drop(columns='Survived')

In [24]:
Y = df['Survived']

In [25]:
X

,Pclass,Sex,SibSp,Parch,Fare,Embarked_Cherbourg,Embarked_Queenstown,Embarked_Southampton
0,-1.568865,-1.359197,-0.462644,-0.469267,1.675922,2.083270,-0.298135,-1.648919
1,0.824107,0.735729,-0.462644,-0.469267,-0.234102,-0.480015,-0.298135,0.606458
2,0.824107,0.735729,-0.462644,-0.469267,-0.176222,2.083270,-0.298135,-1.648919
3,0.824107,0.735729,-0.462644,-0.469267,-0.147283,-0.480015,-0.298135,0.606458
4,0.824107,0.735729,-0.462644,-0.469267,-0.407741,2.083270,-0.298135,-1.648919
...,...,...,...,...,...,...,...,...
997755,-0.372379,0.735729,-0.462644,-0.469267,0.228934,-0.480015,-0.298135,0.606458
997756,-1.568865,-1.359197,-0.462644,-0.469267,2.428356,-0.480015,-0.298135,0.606458
997757,0.824107,0.735729,0.442462,-0.469267,-0.291981,-0.480015,-0.298135,0.606458
997758,-0.372379,0.735729,0.442462,-0.469267,-0.523500,-0.480015,-0.298135,0.606458
997759,-1.568865,-1.359197,0.442462,-0.469267,1.126067,-0.480015,-0.298135,0.606458

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
X_train,X_temp,Y_train,Y_temp = train_test_split(X,Y,test_size=0.36,random_state=42)

X_val,X_test,Y_val,Y_test = train_test_split(X_temp,Y_temp,test_size=0.5556,random_state=42)

In [28]:
X_train.shape

(638566, 8)

In [29]:
X_val.shape

(159625, 8)

In [30]:
X_test.shape

(199569, 8)

In [31]:
import tensorflow

In [32]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

In [33]:
model = Sequential([Dense(64,input_shape=(X_train.shape[1],),activation='relu'),
                    Dense(32,activation='relu'),
                    Dense(1,activation='sigmoid')]) #Last hidden layer

f:\Codes\Python\Gen AI\Projects\Titanic Project\.venv\Lib\site-packages\keras\src\layers\core\dense.py:107: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

In [34]:
opt = tensorflow.optimizers.Adam(learning_rate=0.01)
model.compile(optimizer=opt,loss='binary_crossentropy',metrics=['accuracy'])

WARNING:tensorflow:TensorFlow GPU support is not available on native Windows for TensorFlow >= 2.11. Even if CUDA/cuDNN are installed, GPU will not be used. Please use WSL2 or the TensorFlow-DirectML plugin.

In [35]:
from tensorflow.keras.callbacks import EarlyStopping

In [40]:
early_stopping = EarlyStopping(
    monitor="val_loss",
    patience=5,
    mode="min",
    restore_best_weights=True,
)

In [37]:
model.fit(X_train,Y_train,validation_data=(X_val,Y_val),epochs=10,callbacks=[early_stopping])

Epoch 1/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 21s 1ms/step - accuracy: 0.8533 - loss: 0.3360 - val_accuracy: 0.8601 - val_loss: 0.3247
Epoch 2/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 25s 1ms/step - accuracy: 0.8595 - loss: 0.3210 - val_accuracy: 0.8553 - val_loss: 0.3259
Epoch 3/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 24s 1ms/step - accuracy: 0.8604 - loss: 0.3187 - val_accuracy: 0.8612 - val_loss: 0.3155
Epoch 4/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 21s 1ms/step - accuracy: 0.8604 - loss: 0.3179 - val_accuracy: 0.8614 - val_loss: 0.3184
Epoch 5/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 20s 993us/step - accuracy: 0.8610 - loss: 0.3172 - val_accuracy: 0.8622 - val_loss: 0.3152
Epoch 6/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 21s 1ms/step - accuracy: 0.8610 - loss: 0.3170 - val_accuracy: 0.8633 - val_loss: 0.3197
Epoch 7/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 20s 1ms/step - accuracy: 0.8614 - loss: 0.3161 - val_accuracy: 0.8624 - val_loss: 0.3161
Epoch 8/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 21s 1ms/step - accuracy: 0.8614 - loss: 0.3162 - val_accuracy: 0.8609 - val_loss: 0.3190
Epoch 9/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 20s 995us/step - accuracy: 0.8615 - loss: 0.3158 - val_accuracy: 0.8624 - val_loss: 0.3142
Epoch 10/10
19956/19956 ━━━━━━━━━━━━━━━━━━━━ 22s 1ms/step - accuracy: 0.8616 - loss: 0.3152 - val_accuracy: 0.8613 - val_loss: 0.3157

In [38]:
model.save('model.h5')

WARNING:absl:You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.

In [ ]:
model.predict(X_val, Y_val)

4989/4989 ━━━━━━━━━━━━━━━━━━━━ 4s 756us/step - accuracy: 0.8624 - loss: 0.3142

[0.3142200708389282, 0.8624463677406311]